config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :ingredients
  resources :recipes do
    resources :recipe_ingredients
  end
  resources :members, except: [:destroy]
  resources :groups do
    member do
      post :assign
    end
    resources :group_members
  end

  namespace :leader do
    resources :members, only: [:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :directions, presence: true
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients, dependent: :destroy
  has_many :groups
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    if @recipe.save
      flash[:success] = "#{@recipe.title} added!"

      redirect_to recipes_path
    else
      flash[:error] = "Please complete all fields"

      redirect_to new_recipe_path
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    valid_recipe = @recipe.update(recipe_params)
    if params[:recipe][:recipe_ingredients].nil? && valid_recipe

      redirect_to recipe_path(@recipe)
    elsif valid_recipe
      RecipeIngredientCreator.new(recipe_id: params[:id], recipe_ingredients: recipe_ingredient_params)

      redirect_to recipe_path(@recipe)
    else
      render 'Edit'
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy

    flash[:success] = "#{recipe.title} was successfully deleted!"
    redirect_to recipes_path
  end

private
  def recipe_params
    params.require(:recipe).permit(:title, :directions)
  end

  def recipe_ingredient_params
    params.require(:recipe).require(:recipe_ingredients)
    .permit(
      :ingredient_amount,
      :ingredient_id
    )
  end
end

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.label :directions %>
  <%= f.text_field :directions %>

  <%= f.submit 'Create Recipe' %>
<% end %>

app/views/recipes/_ingredient_form.html.erb
<%= form_for @recipe do |f| %>

  <%= f.fields_for :recipe_ingredients, @recipe.recipe_ingredients.build do |recipe_ingredient| %>
    <%= recipe_ingredient.label :ingredient_amount %>
    <%= recipe_ingredient.text_field :ingredient_amount %> &nbsp &nbsp
    <%= recipe_ingredient.label :ingredient_id %>
    <%= recipe_ingredient.collection_select :ingredient_id, Ingredient.all, :id, :item %>
  <% end %>

  <%= f.submit 'Add' %>
<% end %>

app/views/recipes/edit.html.erb
<h2>Edit <%= @recipe.title %> here!</h2>

<%= render partial: "form" %>

app/views/recipes/index.html.erb
<h2>Recipes</h2>
<% if current_leader? %>
  <%= link_to 'Add Recipes', new_recipe_path %>
<% end %>

<ul>
  <% @recipes.each do |recipe| %>
  <li class=recipe <%= recipe.title %>
  <li><%= link_to recipe.title, recipe_path(recipe) %>
    <% if current_leader? %>
      <%= link_to 'Edit', edit_recipe_path(recipe) %>
      <%= link_to 'Delete', recipe_path(recipe), method: 'Delete' %></li>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<h2>Add Recipe here!</h2>

<%= render partial: "form" %>

app/views/recipes/show.html.erb
<h2><%= @recipe.title %> Recipe</h2>

<% if current_leader? %>
  <%= link_to 'Add Recipes', new_recipe_path %>

  <%= link_to 'Edit', edit_recipe_path(@recipe) %>
  <%= link_to 'Delete', recipe_path(@recipe), method: 'Delete' %>
  <br>
  <%= render partial: "ingredient_form" %>
<% end %>

<ul class=recipe_ingredients>
  <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
    <% if recipe_ingredient.ingredient %>
      <li><%= recipe_ingredient.ingredient_amount %>  <%= recipe_ingredient.ingredient.item %></li>
    <% end %>
  <% end %>
</ul>
Directions:
<br>
<%= @recipe.directions %>