config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :ingredients
  resources :recipes do
    resources :recipe_ingredients
  end
  resources :members, except: [:destroy]
  resources :groups do
    member do
      post :assign
    end
    resources :group_members
  end

  namespace :leader do
    resources :members, only: [:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :start, presence: true
  has_many :group_members
  has_many :members, through: :group_members, dependent: :destroy
  belongs_to :recipe

  def assign_ingredients
    ingreds = recipe.ingredients.shuffle.to_a
    members.each do |member|
      member.ingredient_id = ingreds.pop.id
      member.save!
    end
  end

  def get_assignments
    return unless members.all? { |m| m.ingredient_id }
    members.each_with_object({}) do |member, results|
      amount = RecipeIngredient.find_by(
        recipe_id: recipe.id,
        ingredient_id: member.ingredient_id
       ).ingredient_amount
      results[member.name] = [member.ingredient.item, amount]
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @assignments = @group.get_assignments
  end

  def assign
    @group = Group.find(params[:id])
    if @group.get_assignments.nil?
      recipe = @group.recipe
      @group.assign_ingredients
    end
    redirect_to group_path(@group)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.create(group_params)
    if @group.save
      flash[:success] = "#{@group.title} added!"

      redirect_to groups_path
    else
      flash[:error] = "Please complete all fields"

      redirect_to new_group_path
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    valid_group = @group.update(group_params)
    if params[:group][:group_members].nil? && valid_group

      redirect_to group_path(@group)
    elsif valid_group
      GroupMemberCreator.new(group_id: params[:id], member_id: group_member_params[:member_id])

      redirect_to group_path(@group)
    else
      render 'Edit'
    end
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy

    flash[:success] = "#{group.title} was successfully deleted!"
    redirect_to groups_path
  end

  private
    def group_params
      params.require(:group).permit(:title, :start, :recipe_id)
    end

    def group_member_params
      params.require(:group).require(:group_members)
      .permit(
        :group_id,
        :member_id
      )
    end
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :recipe_id %>
  <%= f.collection_select :recipe_id, Recipe.all, :id, :title %>

  <%= f.label :start %>
  <%= f.date_field :start %>

  <%= f.submit 'Create Group' %>
<% end %>

app/views/groups/_member_form.html.erb
<%= form_for @group do |f| %>

  <%= f.fields_for :group_members, @group.group_members.build do |group_member| %>
    <%= group_member.label :member_id %>
    <%= group_member.collection_select :member_id, Member.all, :id, :name %>
  <% end %>

  <%= f.submit 'Add' %>
<% end %>

app/views/groups/edit.html.erb
<h2>Edit <%= @group.title %> here!</h2>

<%= render partial: "form" %>

app/views/groups/index.html.erb
<h2>Groups</h2>
<% if current_leader? %>
  <%= link_to 'Create Group', new_group_path %>
<% end %>

<ul>
  <% @groups.each do |group| %>
  <li class=group <%= group.title %>
  <li>Meals start on: <%= group.start %> for
    <%= link_to group.title, group_path(group) %>
    <% if current_leader? %>
      <%= link_to 'Edit', edit_group_path(group) %>
      <%= link_to 'Delete', group_path(group), method: 'Delete' %></li>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/groups/new.html.erb
<h2>Make Group here!</h2>

<%= render partial: "form" %>

app/views/groups/show.html.erb
<h2><%= @group.title %> Group</h2>
<% if current_leader? %>
  <%= link_to 'Edit', edit_group_path(@group) %>
  <%= link_to 'Delete', group_path(@group), method: 'Delete' %>
<% end %>
<br>
<% if current_leader? %>
  <br>
  <%= render partial: "member_form" %>
  <br>
<% end %>
<br>
Recipe Name: <%= @group.recipe.title %>
<br>
Start: <%= @group.start %>
<br>
<br>
Group Members:
<ul class=group_members>
    <% @group.group_members.each do |group_member| %>
    <% unless group_member.member_id.nil? %>
      <li><%= group_member.member.name %> | <%= @assignments[group_member.member.name] if @assignments %> </li>
    <% end %>
  <% end %>
</ul>

<% if current_leader? %>
  <%= button_to 'Assign Ingredients', assign_group_path(@group) %>
<% end %>