config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :ingredients
  resources :recipes do
    resources :recipe_ingredients
  end
  resources :members, except: [:destroy]
  resources :groups do
    member do
      post :assign
    end
    resources :group_members
  end

  namespace :leader do
    resources :members, only: [:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :item, presence: true, uniqueness: true
  has_many :recipe_ingredients
  has_many :members
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.create(ingredient_params)
    if params[:commit] == 'Save and Add More Ingredients' && @ingredient.save
      flash[:success] = "#{@ingredient.item} added!"

      redirect_to new_ingredient_path
    elsif params[:commit] == 'Create Ingredient' && @ingredient.save
      flash[:success] = "#{@ingredient.item} added!"

      redirect_to ingredients_path
    else
      flash[:error] = "Really!? there is only one field to complete... try again!"

      redirect_to new_ingredient_path
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path
    else
      render 'Edit'
    end
  end

  def destroy
    ingredient = Ingredient.find(params[:id])
    ingredient.destroy

    flash[:success] = "#{ingredient.item} was successfully deleted!"
    redirect_to ingredients_path
  end

private
  def ingredient_params
    params.require(:ingredient).permit(:item)
  end
end

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>
  <%= f.label :item %>
  <%= f.text_field :item %>

  <%= f.submit 'Save and Add More Ingredients' %>
  <%= f.submit 'Create Ingredient' %>
<% end %>

app/views/ingredients/edit.html.erb
<h2>Edit <%= @ingredient.item %> here!</h2>

<%= render partial: "form" %>

app/views/ingredients/index.html.erb
<h2>Available Ingredients</h2>
<% if current_leader? %>
  <%= link_to 'Add Ingredients', new_ingredient_path %>
<% end %>

<ul>
  <% @ingredients.each do |ingredient| %>
  <li class=ingredient <%= ingredient.item %>
  <li><%= ingredient.item %>
    <% if current_leader? %>
      <%= link_to 'Edit', edit_ingredient_path(ingredient) %>
      <%= link_to 'Delete', ingredient_path(ingredient), method: 'Delete' %></li>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/ingredients/new.html.erb
<h2>Add Ingredient here!</h2>

<%= render partial: "form" %>