config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :ingredients
  resources :recipes do
    resources :recipe_ingredients
  end
  resources :members, except: [:destroy]
  resources :groups do
    member do
      post :assign
    end
    resources :group_members
  end

  namespace :leader do
    resources :members, only: [:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :email, uniqueness: true, presence: true
  validates :role, presence: true
  validates :username, uniqueness: true, presence: true
  validates_presence_of :password, require: true, on: :create

  has_secure_password

  enum role: {
    member: 0,
    leader: 1,
  }

  has_many :group_members
  belongs_to :ingredient, optional: true
end

app/controllers/leader/members_controller.rb
class Leader::MembersController < Leader::BaseController
  def show
    @leader = Member.find(params[:id])
  end

  def destroy
    Member.destroy(params[:id])

    redirect_to members_path
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    render :file => "#{Rails.root}/public/404" unless current_leader?
    @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.create(member_params)
    if params[:commit] == 'Create Account' && @member.save
      session[:member_id] = @member.id
      flash[:success] = "Welcome, #{@member.name}!"

      redirect_to member_path(@member)
    else
      flash[:error] = 'Registration fail, Please try again!'

      redirect_to new_member_path
    end
  end
   def edit
     @member = Member.find(params[:id])
   end

   def update
     @member = Member.find(params[:id])
     if @member.update(member_params)
       redirect_to members_path
     else
       render 'Edit'
     end
   end

   # def destroy
   #   member = Member.find(params[:id])
   #   member.destroy
   #
   #   flash[:success] = "#{member.name} was successfully deleted!"
   #   redirect_to members_path
   # end

private
  def member_params
    params.require(:member)
    .permit(
      :name,
      :username,
      :password,
      :role,
      :email,
      :ingredient_id
    )
  end
end

app/views/members/_form.html.erb
<%= form_for @member do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :role %>
  <%= f.text_field :role %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.submit 'Create Account' %>
<% end %>

app/views/members/edit.html.erb
<h2>Edit <%= @member.name %> here!</h2>

<%= render partial: "form" %>

app/views/members/index.html.erb
<center>
  <h1>Stone Soup Members</h1>
</center>

<ul>
  <% @members.each do |member| %>
  <li class=member id='member_<%= member.id %>' >
      <%= link_to member.name, member_path(member) %>
      <%= link_to 'Edit', edit_member_path(member) %>
    <% if current_member.id != member.id %>
      <%= link_to 'Delete', leader_member_path(member), method: 'Delete' %>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/members/new.html.erb
<h2>Become Member here!</h2>

<%= render partial: "form" %>

app/views/members/show.html.erb
<% if current_member %>
  <%= link_to "Log out", logout_path %>
<% end %>
<br>
<%= @member.name %>
<br>
<%= @member.email %>
<br>
<%= @member.role %>

<br>
  <h2>Your ingredient this week:<h2>
  <%= @member.ingredient.item unless @member.ingredient_id.nil? %>